"use client";

import { useState } from "react";

interface ShareActionsProps {
  run: {
    publicId: string;
    scenarioId: string;
    connectorKind: string;
    model: string;
    status: string;
    score: {
      total: number;
      passed: number;
      totalExpectations: number;
      failureBreakdown: Record<string, number>;
    } | null;
    findings: {
      mode: string;
      stepIndex: number;
      detail: string;
      confidence: number;
    }[];
    startedAt: string;
    finishedAt: string | null;
  };
}

export function ShareActions({ run }: ShareActionsProps) {
  const [copied, setCopied] = useState<string | null>(null);

  function generateGitHubMarkdown(): string {
    const score = run.score;
    const lines: string[] = [];

    lines.push(`## 🐕 Dogfood Run Report`);
    lines.push("");
    lines.push(`**Score:** ${score?.total ?? "—"}/100`);
    lines.push(`**Model:** ${run.model}`);
    lines.push(`**Connector:** ${run.connectorKind}`);
    lines.push(`**Scenario:** ${run.scenarioId}`);
    lines.push(`**Status:** ${run.status}`);
    lines.push(`**Started:** ${run.startedAt}`);
    if (run.finishedAt) lines.push(`**Finished:** ${run.finishedAt}`);
    lines.push("");

    if (score) {
      lines.push(`**Expectations:** ${score.passed}/${score.totalExpectations} passed`);
      lines.push("");
      lines.push("<details>");
      lines.push("<summary>Failure breakdown</summary>");
      lines.push("");
      lines.push("| Mode | Count |");
      lines.push("|------|-------|");
      for (const [mode, count] of Object.entries(score.failureBreakdown)) {
        lines.push(`| ${mode} | ${count} |`);
      }
      lines.push("");
      lines.push("</details>");
    }

    if (run.findings.length > 0) {
      lines.push("");
      lines.push("<details>");
      lines.push(`<summary>Findings (${run.findings.length})</summary>`);
      lines.push("");
      for (const f of run.findings) {
        lines.push(`- **${f.mode}** (step ${f.stepIndex}, ${(f.confidence * 100).toFixed(0)}%): ${f.detail}`);
      }
      lines.push("");
      lines.push("</details>");
    }

    lines.push("");
    lines.push(`---`);
    lines.push(`*Generated by [Dogfood](https://dogfood.dev) — eat your own food.*`);

    return lines.join("\n");
  }

  function generateSlackSummary(): string {
    const score = run.score;
    const scoreStr = score ? `${score.total}/100 (${score.passed}/${score.totalExpectations} passed)` : "—";
    const topFindings = run.findings.slice(0, 3).map(
      (f) => `${f.mode}@step${f.stepIndex}`,
    );
    const findingsStr = topFindings.length > 0 ? ` | Issues: ${topFindings.join(", ")}` : "";
    const slug = run.scenarioId.length > 30 ? run.scenarioId.slice(0, 27) + "…" : run.scenarioId;

    let summary = `🐕 Dogfood: ${run.model} on ${slug} → ${scoreStr}${findingsStr}`;

    // Trim to ≤ 400 chars
    if (summary.length > 400) {
      summary = summary.slice(0, 397) + "…";
    }

    return summary;
  }

  async function copyToClipboard(text: string, key: string) {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(key);
      setTimeout(() => setCopied(null), 2000);
    } catch {
      const textarea = document.createElement("textarea");
      textarea.value = text;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(key);
      setTimeout(() => setCopied(null), 2000);
    }
  }

  async function copyAsGitHub() {
    copyToClipboard(generateGitHubMarkdown(), "github");
  }

  async function copyAsSlack() {
    copyToClipboard(generateSlackSummary(), "slack");
  }

  return (
    <div className="flex items-center gap-2">
      <button
        type="button"
        onClick={copyAsGitHub}
        className="inline-flex cursor-pointer items-center gap-1.5 border border-[var(--border)] bg-[var(--surface)] px-3 py-1.5 text-xs text-[var(--dim)] hover:border-[var(--accent)] hover:text-[var(--accent)]"
      >
        {copied === "github" ? "✓ Copied!" : "📋 Copy as GitHub issue"}
      </button>
      <button
        type="button"
        onClick={copyAsSlack}
        className="inline-flex cursor-pointer items-center gap-1.5 border border-[var(--border)] bg-[var(--surface)] px-3 py-1.5 text-xs text-[var(--dim)] hover:border-[var(--accent)] hover:text-[var(--accent)]"
      >
        {copied === "slack" ? "✓ Copied!" : "💬 Copy as Slack summary"}
      </button>
    </div>
  );
}
