import type { HNPost } from "@dogfood/shared";

interface ArchetypeBucket {
  name: string;
  description: string;
  posts: HNPost[];
}

const REDDITS = ["r/LocalLLaMA", "r/MachineLearning", "r/programming"];
const DEV_TOOLS = ["r/devtool", "r/ShowHN"];

async function fetchLast200(): Promise<HNPost[]> {
  const resp = await fetch(
    "https://hn.algolia.com/api/v1/search?tags=story&hitsPerPage=200",
    { signal: AbortSignal.timeout(30_000) },
  );
  if (!resp.ok) {
    throw new Error(`HN API failed: ${resp.status}`);
  }

  const data = (await resp.json()) as { hits: HNPost[] };
  return data.hits.filter((post) => {
    const authorLower = post.author?.toLowerCase() ?? "";
    return (
      REDDITS.includes(authorLower) ||
      DEV_TOOLS.includes(authorLower) ||
      post.title.toLowerCase().includes("show hn")
    );
  });
}

const buckets: ArchetypeBucket[] = [
  {
    name: "problem-first post",
    description:
      "Posts about specific problems with 'here is how I solved it' structure. Often benchmark numbers, before/after stats, or explicit 'I struggled' narratives.",
    posts: [],
  },
  {
    name: "benchmark post",
    description:
      "Performance comparisons with charts or data. 'X runs in 0.3s, Bun is 10x faster' style. Focus on numbers and visual proof.",
    posts: [],
  },
  {
    name: "meta-tool post",
    description:
      "Reflections on the tooling ecosystem or developer workflow. 'How I automate X with Y' or 'Why I stopped using Z'. Opinionated, often controversial takes.",
    posts: [],
  },
  {
    name: "opinionated hot-take",
    description:
      "Strong, takes that may or may not be true. 'React is dead' or 'Type systems are unnecessary complexity' style. Usually generates engagement through disagreement.",
    posts: [],
  },
];

async function main() {
  console.log("Fetching last 200 posts from targeted subreddits...");
  console.log(`Target: ${REDDITS.join(", ")}, ${DEV_TOOLS.join(", ")}`);

  const allPosts = await fetchLast200();

  console.log(`Total posts collected: ${allPosts.length}`);

  const uniquePosts = new Map<string, HNPost>();
  for (const post of allPosts) {
    if (!uniquePosts.has(post.id)) {
      uniquePosts.set(post.id, post);
    }
  }

  console.log(`Unique posts: ${uniquePosts.size}`);

  for (const post of uniquePosts.values()) {
    const title = post.title.toLowerCase();
    const text = post.title.toLowerCase();

    if (title.includes("solved") || title.includes("fixed") || title.includes("improved")) {
      if (title.includes("struggle") || title.includes("struggled")) {
        buckets[0].posts.push(post);
      }
    }

    if (
      text.includes("benchmark") ||
      text.includes("x") ||
      text.includes("bun") ||
      text.includes("faster") ||
      text.includes("slower")
    ) {
      buckets[1].posts.push(post);
    }

    if (
      text.includes("tool") ||
      text.includes("workflow") ||
      text.includes("automate") ||
      text.includes("why") ||
      text.includes("stopped")
    ) {
      buckets[2].posts.push(post);
    }

    if (
      title.includes("is dead") ||
      title.includes("unnecessary") ||
      title.includes("bloated") ||
      title.includes("overkill") ||
      title.includes("complexity") ||
      title.includes("vs")
    ) {
      buckets[3].posts.push(post);
    }
  }

  const lines: string[] = [];
  lines.push("# 📢 Post Archetypes — Dogfood Launch Research");
  lines.push("");
  lines.push(`> Fetched ${uniquePosts.size} unique posts from ${REDDITS.join(", ")} and ${DEV_TOOLS.join(", ")}`);
  lines.push("> Analyzed by archetype keyword matching. Title field used for categorization.");
  lines.push("");

  for (const bucket of buckets) {
    lines.push(`## ${bucket.name}`);
    lines.push(bucket.description);
    lines.push("");
    lines.push(
      bucket.posts
        .map((p) => `| [${p.points}] [${p.timeAgo}] [${p.title}](https://news.ycombinator.com/item?id=${p.id}) |`)
        .slice(0, 5)
        .join("\n"),
    );
    if (bucket.posts.length > 0) {
      lines.push(`… ${bucket.posts.length - 5} more in this bucket\n`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by [Dogfood](https://dogfood.dev) — post-archetypes research.*");

  const fs = await import("fs");
  const outputPath = "/Users/abhay/code/dogfood/docs/post-archetypes.md";
  fs.writeFileSync(outputPath, lines.join("\n"), "utf-8");

  console.log(`Written to ${outputPath}`);
}

main().catch((err) => {
  console.error("Fatal:", err);
  process.exit(1);
});
